### ISSUE TITLE
wechat-start运行时出现错误

### ISSUE THREAD

**Issue by railsfans** [goofansu/wechat-starter#11]
运行下过来的例子首先出现如下错误
NoMethodError (undefined method `user_omniauth_authorize_path' for #<DeviseFailure:0x00000007262508>
Did you mean?  user_wechat_omniauth_authorize_path):
  lib/devise_failure.rb:3:in `redirect_url'
我把user_omniauth_authorize_path改成user_wechat_omniauth_authorize_path访问主页，出现
Not found. Authentication passthru. 错误。请教一下怎么解决

**Comment by goofansu** [comment]
这是因为最新版devise换API了，#10 应该解决了这个问题。更新下代码，然后`bundle install`

**Comment by goofansu** [comment]
最近我会抽空加一个支持rails 5的分支
