### ISSUE TITLE
{"errcode":-107,"errmsg":"token check timeout"}

### ISSUE THREAD

**Issue by owyongsk** [goofansu/wechat-starter#12]
根据readme 指示安装后，在公众平台管理测试号提交 接口配置信息重视配置失败。

sandboxinfo 回复总是 {"errcode":-107,"errmsg":"token check timeout"}

我的服务器在国外，timeout 在 wechat.yml 已经改为30 了。

**Comment by goofansu** [comment]
比较有可能是dns的问题，请问最近还有这个问题吗？

**Comment by owyongsk** [comment]
还没试呢，试后再跟你说，麻烦你了。
