### ISSUE TITLE
ActionView::Template::Error (undefined method `trusted_domain_fullname'

### ISSUE THREAD

**Issue by tianbymy** [goofansu/wechat-starter#16]
ActionView::Template::Error (undefined method `trusted_domain_fullname' for Users::RegistrationsController:Class):
    1: <script src="http://res.wx.qq.com/open/js/jweixin-1.0.0.js"></script>
    2: <%= wechat_config_js debug: false, api: %w(closeWindow) -%>
    3:
    4: <div class="weui_msg">
    5:   <div class="weui_text_area">
  app/views/devise/registrations/new.html.erb:2:in `_app_views_devise_registrations_new_html_erb__1080018874292238542_70288383590620'

**Comment by Eric-Guo** [comment]
Need configure [trusted_domain_fullname](https://github.com/eric-Guo/wechat#js-sdk-helper) at wechat.yml.

```
development:
  <<: *default
  trusted_domain_fullname: "http://your_dev.proxy.qqbrowser.cc"
```
