### ISSUE TITLE
{"errcode":-107,"errmsg":"token check timeout"}

### ISSUE THREAD

**Issue by ikylin** [goofansu/wechat-starter#17]
同样是根据readme一路下来，在配置微信接口的时候总是报这个错误，导致失败
环境如下：
ubuntu 14.04 
ruby 2.3 
rails4.2.6
ngrok 端口映射 
保存时后台日志显示已经200返回
Started GET "/wechat?signature=b39266dd633c5b5d012921bf4c7f058b6f6660e1&echostr=1078978666882000783&timestamp=1470751247&nonce=579122087" for 58.247.206.145 at 2016-08-09 22:00:49 +0800
Cannot render console from 58.247.206.145! Allowed networks: 127.0.0.1, ::1, 127.0.0.0/127.255.255.255
Processing by WechatsController#show as */*
  Parameters: {"signature"=>"b39266dd633c5b5d012921bf4c7f058b6f6660e1", "echostr"=>"1078978666882000783", "timestamp"=>"1470751247", "nonce"=>"579122087"}
  Rendered text template (0.0ms)
Completed 200 OK in 1ms (Views: 0.6ms | ActiveRecord: 0.0ms)

**Comment by Eric-Guo** [comment]
> Cannot render console from 58.247.206.145! Allowed networks: 127.0.0.1, ::1, 127.0.0.0/127.255.255.255

`rails s -b 0.0.0.0` 试试？

**Comment by ikylin** [comment]
dev@iZ28r4jaqj6Z:~/demo/wtest$ rails s -b 0.0.0.0
=> Booting Puma
=> Rails 4.2.6 application starting in development on http://0.0.0.0:3000
=> Run `rails server -h` for more startup options
=> Ctrl-C to shutdown server
[21093] Puma starting in cluster mode...
[21093] * Version 3.4.0 (ruby 2.3.0-p0), codename: Owl Bowl Brawl
[21093] * Min threads: 1, max threads: 6
[21093] * Environment: development
[21093] * Process workers: 2
[21093] * Preloading application
[21093] * Listening on tcp://0.0.0.0:3000
[21093] Use Ctrl-C to stop

后台：
Started GET "/wechat?signature=feb07ad4bc11a7abfdd55478e94af724cc8a6ebe&echostr=645035266912800508&timestamp=1470795492&nonce=1700989632" for 140.207.54.77 at 2016-08-10 10:18:12 +0800
Cannot render console from 140.207.54.77! Allowed networks: 127.0.0.1, ::1, 127.0.0.0/127.255.255.255
Processing by WechatsController#show as */*
  Parameters: {"signature"=>"feb07ad4bc11a7abfdd55478e94af724cc8a6ebe", "echostr"=>"645035266912800508", "timestamp"=>"1470795492", "nonce"=>"1700989632"}
  Rendered text template (0.0ms)
Completed 200 OK in 3ms (Views: 2.9ms | ActiveRecord: 0.0ms)

微信配置前端返回：
{"errcode":-107,"errmsg":"token check timeout"}

**Comment by ikylin** [comment]
去掉了puma，使用WEBrick
rails s -b 0.0.0.0 之后微信段配置成功

**Comment by Eric-Guo** [comment]
呃。。。这不科学。。。

**Comment by goofansu** [comment]
puma 是有这个问题，我是在nginx里配置了proxy_pass，所以没问题

我以前在ruby-china上提过问题：https://ruby-china.org/topics/26468

附上nginx配置

``` nginx
upstream puma {
  server 127.0.0.1:3000;
}

server {
  listen 80;
  server_name m.ggrok.com;

  try_files $uri @puma;
  location @puma {
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header Host $http_host;
    proxy_redirect off;
    proxy_pass http://puma;
  }
}
```
