### ISSUE TITLE
二维码失效了？

### ISSUE THREAD

**Issue by zixzixzix** [goofansu/wechat-starter#19]
503 Service Unavailable

**Comment by Eric-Guo** [comment]
支持支付的公众号必须是服务号，@goofansu 的这个号现在跑正式环境了，wechat-starter的代码基本没啥问题的。

**Comment by goofansu** [comment]
@Eric-Guo 也不算正式环境，是放一些自己的api试验，如果不带支付，用测试号应该就行了

**Comment by zixzixzix** [comment]
readMe里的二维码是做什么的？不是关注用的吗？

**Comment by goofansu** [comment]
不是，只是个例子，现在那个帐号已经做别的用了，所以没用了

------------------
Kind Regards,
goofansu

**Comment by goofansu** [comment]
@zixzixzix 已部署到heroku上，可以扫最新的二维码查看
