### ISSUE TITLE
Pay 0.01 with cash failed in some circumstances

### ISSUE THREAD

**Issue by goofansu** [goofansu/wechat-starter#2]
From @Eric-Guo,

An account without bank cards fails to pay 0.01 with cash in Wechat v6.3.13.

**Comment by goofansu** [comment]
Cannot reproduce with my Wechat, the same version.

You can inspect with `puts` the result of https://github.com/goofansu/wechat-starter/blob/master/app/controllers/home_controller.rb#L18

**Comment by Eric-Guo** [comment]
Thanks, @WayTang found it.
