### ISSUE TITLE
post /wechat?... 请求出现问题，使用的是heroku的服务器

### ISSUE THREAD

**Issue by frankgu** [goofansu/wechat-starter#21]
首先我将项目push到heroku的服务器当中，然后根据readme配置了`config/application.yml.sample`文件中的 `wechat_app_id`, `wechat_secret`和`wechat_token`的三个选项（修改成我自己测试公众号的信息）。

[测试公众号链接](http://mp.weixin.qq.com/debug/cgi-bin/sandbox?t=sandbox/login)

在测试公众号中我按照提示成功配置了接口信息，参考下方图片。
![image](https://cloud.githubusercontent.com/assets/3247420/18037028/6a87486e-6d48-11e6-8f1b-309ab14d0c83.png)

当我成功关注了自己的测试公众号之后， 无论我发送什么信息给公众号， 公众号都会返回`该公众号暂时无法提供服务，请稍后再试`的提示语。 当我使用命令 `rake wechat:menu_create`时，可以成功修改测试公众号的菜单。 

当我在本地的服务器测试查看日志之后， 出现了以下错误， 参考下方图片
![image](https://cloud.githubusercontent.com/assets/3247420/18037058/2f17df22-6d49-11e6-9670-a6bf9e186c70.png)

不知道我的问题出在了哪儿？求两位大神帮忙看看 @Eric-Guo @goofansu 万分感谢

**Comment by goofansu** [comment]
这个问题我不知道什么原因，我有空了部署一下到heroku看看

**Comment by goofansu** [comment]
wechat-starter在production和development模式下，默认是开启加密的。

现在改为默认不加密，因为大家一般都用测试帐号进行测试，测试帐号是不加密的。

在生产环境中如果要开启加密，就在application.yml中增加一行：

```
wechat_encrypt_mode: true
```

你更新一下代码，不用做改动，直接传到heroku就能运行了。

**Comment by frankgu** [comment]
@goofansu  成功了， 非常感谢！

**Comment by goofansu** [comment]
@frankgu 不过授权登陆以后跳转到注册好像有问题，我下午看了下还没搞定，回家再看看
