### ISSUE TITLE
有必要升级到rails 5吗？

### ISSUE THREAD

**Issue by goofansu** [goofansu/wechat-starter#25]
@Eric-Guo 现在用5的人多吗？

**Comment by Eric-Guo** [comment]
反正我在用，升起来很容易的 `rails app:update`，Rails官方永远支持最近的两个版本，rails master版本已经是5.1了，所以反正早晚也要升。。

**Comment by goofansu** [comment]
@Eric-Guo `rails app:update` 这命令没有嘛，我是rails 5.0.0.1

**Comment by goofansu** [comment]
@Eric-Guo 有了，原来要装一下`railties`

**Comment by Eric-Guo** [comment]
要先把项目Gemfile的rails版本升级到5.0.0.1，然后在项目的Gemfile所在目录运行

**Comment by goofansu** [comment]
@Eric-Guo heroku上已经是rails 5了
