### ISSUE TITLE
访问 http://my-domain.com 出错

### ISSUE THREAD

**Issue by frankgu** [goofansu/wechat-starter#31]
首先我根据测试公众号的信息配置了`wechat_app_id`,`wechat_secret`,`wechat_token`（没有设置wx_pay的信息），并将项目推送至heroku服务器。 然后我用自己的微信关注了测试公众号之后给公众号发送消息，可以正常返回`echo:消息`。
但是当我把微信自定义菜单栏修改为如下，并推送至微信自定义菜单栏：

![image](https://cloud.githubusercontent.com/assets/3247420/18335807/34c3adac-7550-11e6-988e-f021d19dca87.png)

url是自己的heroku服务器的url的时候，当我点击测试公众号的相应的菜单，界面出错：

![image](https://cloud.githubusercontent.com/assets/3247420/18335863/9641238e-7550-11e6-840a-78234e21c9f1.png)

服务器的错误信息为：

![image](https://cloud.githubusercontent.com/assets/3247420/18335895/caf0a60e-7550-11e6-8dd1-45ab3eb83316.png)

求大神帮忙找一下错误， 不知道我的问题出在了哪儿，卡了几天了。谢谢！ @goofansu

**Comment by goofansu** [comment]
请检查一下：公众平台测试帐号里“网页账号	网页授权获取用户基本信息”，这里的URL改成heroku的地址了吗？

**Comment by frankgu** [comment]
以下图片是我的测试微信公众号的配置信息，我并没有找到“网页账号 网页授权获取用户基本信息”这个选项。
![image](https://cloud.githubusercontent.com/assets/3247420/18336277/cd1ec6f6-7553-11e6-918e-a835543104ff.png)

**Comment by goofansu** [comment]
网页里搜索，肯定有的

**Comment by libruce** [comment]
拉到下面：
![a8765ec2-1e59-4ba2-81e7-b70e89cbfe65](https://cloud.githubusercontent.com/assets/1838596/18336368/2b58f89e-75b9-11e6-8f33-bb0d57568f11.png)

**Comment by frankgu** [comment]
找到了， 我修改了相应的值 并将值为了heroku的服务器， 但是问题还是存在， 服务器的错误信息还是跟问题反馈的信息一样

**Comment by frankgu** [comment]
可以了！是我的问题, 在天蝎网页授权获取用户基本信息时，不应该填写http://抬头信息，只填写domain的信息就可以了. (ex: my-domain.com)

**Comment by goofansu** [comment]
@frankgu 微信的锅，居然不提示不能填写http，有空帮忙写个wiki啊，提醒后人

**Comment by frankgu** [comment]
@goofansu 微信也有[提示](http://mp.weixin.qq.com/wiki/17/c0f37d5704f0b64713d5d2c37b468d75.html)， 不过需要点进相应的界面看小字才可以。我可以写一个`从零开始使用微信测试公众号, heroku服务器配置wechat-starter`的教程。 如果你觉得可以的话。还有一个就是能不能把wiki的链接放到readme里面，要不是你说有wiki，我之前一直都没有往wiki的选项里面看。 其实里面已经有一个基本配置的教程了， 要是早点看到这个教程的话，我应该就能够自己解决问题了。 谢谢！

**Comment by goofansu** [comment]
@frankgu 谢谢你的意见，已经加了wiki的链接
