### ISSUE TITLE
授权后的响应很慢

### ISSUE THREAD

**Issue by YUFENGWANG** [goofansu/wechat-starter#34]
code=021KGF7T0iqvnT1UCE4T0yvH7T0KGF7o&state=bdef200a0df9e8f221c5825cf23f4e19154ee79e5df0b8bf 。点击确认登陆后，执行这个的响应时间平均都在两s左右。我的vps是国外的。是不是主要是因为网络原因？

**Comment by goofansu** [comment]
应该是，这个是微信那边的响应慢，我部署在青云的服务器，也是时快时慢。你可以选择腾讯云试试
