### ISSUE TITLE
想要支持 多服务号，要打多少补丁，希望把多服务号配置都存到数据库

### ISSUE THREAD

**Issue by tdseed** [goofansu/wechat-starter#36]
这是个扩展问题，可否给个建议

**Comment by Eric-Guo** [comment]
https://github.com/Eric-Guo/wechat/issues/166
https://github.com/Eric-Guo/wechat/issues/118
类似问题。

**Comment by goofansu** [comment]
这个问题先关闭了，此demo主要是为了演示几个核心功能，目前来看还不会支持多服务号。
